/*
 * This code is distributed under terms of GNU GPLv2.
 * *See LICENSE file.
 * ©UKRINFORM 2011-2012
 */

package RibbonProber;

/**
 * Main frame class
 * @author Stanislav Nepochatov
 */
public class mainFrame extends javax.swing.JFrame {
    
    /** Creates new form mainFrame */
    public mainFrame() {
        initComponents();
    }
    
    /**
     * Add message to gui list
     * @param message 
     */
    public synchronized void addToLog(String message) {
        this.logArea.setText(
                this.logArea.getText()  + message);
        this.logArea.setCaretPosition(this.logArea.getText().length());
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        commandBox = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        commandField = new javax.swing.JTextPane();
        launchBut = new javax.swing.JButton();
        ipField = new javax.swing.JTextField();
        connectBut = new javax.swing.JButton();
        portField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pasteBut = new javax.swing.JButton();
        flushBut = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        logArea = new javax.swing.JTextArea();
        helpBut = new javax.swing.JButton();
        flushJournalBut = new javax.swing.JButton();
        levelBox = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Дебагер протоколу системи \"Стрічка\"");

        commandBox.setModel(new javax.swing.DefaultComboBoxModel(ProtocolDecription.getCommandList(-1)));
        commandBox.setToolTipText("");

        jScrollPane1.setViewportView(commandField);

        launchBut.setForeground(new java.awt.Color(153, 0, 0));
        launchBut.setText("Послати!");
        launchBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                launchButActionPerformed(evt);
            }
        });

        ipField.setText("127.0.0.1");

        connectBut.setForeground(new java.awt.Color(204, 102, 0));
        connectBut.setText("З'єднати");
        connectBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                connectButActionPerformed(evt);
            }
        });

        portField.setText("3003");

        jLabel1.setText("Команда");

        jLabel2.setText("Адреса сервера");

        jLabel3.setText("Порт");

        pasteBut.setText("Вставити");
        pasteBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasteButActionPerformed(evt);
            }
        });

        flushBut.setText("Відчистити");
        flushBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flushButActionPerformed(evt);
            }
        });

        logArea.setColumns(20);
        logArea.setEditable(false);
        logArea.setRows(5);
        logArea.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane2.setViewportView(logArea);

        helpBut.setText("?");
        helpBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helpButActionPerformed(evt);
            }
        });

        flushJournalBut.setText("Відчистити журнал");
        flushJournalBut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flushJournalButActionPerformed(evt);
            }
        });

        levelBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Всі команди протоколу", "Команди з’єднання [LEVEL_0]", "Базові команди [LEVEL_1]", "Команди до сервера [LEVEL_2]" }));
        levelBox.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                levelBoxItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(portField)
                        .addGap(18, 18, 18)
                        .addComponent(flushJournalBut)
                        .addGap(18, 18, 18)
                        .addComponent(connectBut))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 675, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(flushBut, javax.swing.GroupLayout.DEFAULT_SIZE, 126, Short.MAX_VALUE)
                            .addComponent(launchBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pasteBut, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(levelBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(commandBox, javax.swing.GroupLayout.PREFERRED_SIZE, 406, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(helpBut)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ipField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(connectBut)
                    .addComponent(portField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(flushJournalBut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(commandBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(helpBut)
                    .addComponent(levelBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(launchBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(pasteBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(flushBut))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void connectButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_connectButActionPerformed
        RibbonProber.connect();
    }//GEN-LAST:event_connectButActionPerformed

    private void launchButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_launchButActionPerformed
        if (RibbonProber.outStream != null) {
            this.addToLog("> " + this.commandField.getText() + "\n");
            RibbonProber.outStream.println(this.commandField.getText());
        } else {
            this.addToLog("ПОМИЛКА: немає з'єднання з сервером!\n");
        }
    }//GEN-LAST:event_launchButActionPerformed

    private void pasteButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasteButActionPerformed
        if (this.commandField.getText().isEmpty()) {
            this.commandField.setText(this.commandBox.getSelectedItem() +
                    ProtocolDecription.getPaste((String) this.commandBox.getSelectedItem()));
        } else {
            this.commandField.setText(this.commandField.getText() + "\n"
                + this.commandBox.getSelectedItem() +
                    ProtocolDecription.getPaste((String) this.commandBox.getSelectedItem()));
        }
    }//GEN-LAST:event_pasteButActionPerformed

    private void flushButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flushButActionPerformed
        this.commandField.setText("");
    }//GEN-LAST:event_flushButActionPerformed

    private void helpButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helpButActionPerformed
        String formatLine = "=====================================================";
        this.addToLog(formatLine + "\nДОВІДКА\n" + formatLine + "\n" + ProtocolDecription.getDoc((String) this.commandBox.getSelectedItem()) + "\n" + formatLine + "\n");
    }//GEN-LAST:event_helpButActionPerformed

    private void flushJournalButActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flushJournalButActionPerformed
        this.logArea.setText("");
    }//GEN-LAST:event_flushJournalButActionPerformed

    private void levelBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_levelBoxItemStateChanged
        this.commandBox.setModel(new javax.swing.DefaultComboBoxModel(ProtocolDecription.getCommandList(this.levelBox.getSelectedIndex() - 1)));
    }//GEN-LAST:event_levelBoxItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new mainFrame().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox commandBox;
    private javax.swing.JTextPane commandField;
    private javax.swing.JButton connectBut;
    private javax.swing.JButton flushBut;
    private javax.swing.JButton flushJournalBut;
    private javax.swing.JButton helpBut;
    public javax.swing.JTextField ipField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton launchBut;
    private javax.swing.JComboBox levelBox;
    private javax.swing.JTextArea logArea;
    private javax.swing.JButton pasteBut;
    public javax.swing.JTextField portField;
    // End of variables declaration//GEN-END:variables
}
